### GET
GET http://localhost:8088/portfolio/read?tipo=portfolio
Content-Type: application/json

### GET
GET http://localhost:8088/portfolio/readPortfolio

### GET
GET http://localhost:8088/portfolio/all

### GET
GET http://localhost:8088/portfolio/get/2

### POST
POST http://localhost:8088/portfolio/create
Content-Type: application/json

{
    "title": "Portfolio App",
    "description": "Portfolio App",
    "repo": "github.com/",
    "techs": ["Angular", "Spring Boot"]
}


### DELETE
DELETE http://localhost:8088/portfolio/delete/4


### PUT
PUT http://localhost:8088/portfolio/update/10
Content-Type: application/json

{    
    "title": "Portfolio App em Angular",
    "description": "Portfolio App em Angular",
    "repo": "github.com/",
    "techs": ["Angular", "Spring Boot"]
}

### PATCH
PATCH http://localhost:8088/portfolio/patch/10
Content-Type: application/json

{    
    "title": "[Novo] Portfolio App em Angular"    
}