spring.config.import=optional:file:.env[.properties]

spring.application.name=hello
server.port=8088

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
# spring.datasource.url=jdbc:postgresql://hidden:5432//postgres.ebtckzlaqfdvxpgvajsj:${DB_PASSWORD}@aws-1-us-west-1.pooler.supabase.com:5432/postgres?user=hidden&password=${DB_PASSWORD}
# spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true