spring.application.name=hello
server.port=8088

spring.datasource.url=jdbc:postgresql://aws-1-us-west-1.pooler.supabase.com:5432/postgres?user=postgres.ebtckzlaqfdvxpgvajsj
spring.datasource.username=postgres.ebtckzlaqfdvxpgvajsj
spring.datasource.password=iwGYC2VHCmJNgONQ

# JPA/Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true